// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package planner_orm

import (
	"database/sql"
	"time"
)

type Reminder struct {
	ID          uint64
	Title       string
	Description sql.NullString
	RemindAt    time.Time
}

type Todo struct {
	ID          uint64
	Title       string
	Description sql.NullString
	Completed   bool
}
